### ISSUE TITLE
Interactive Chart

### ISSUE THREAD

**Issue by iskdjim** [epochjs/epoch#178]
hello,
first to say...really nice lib, real time line chart works really nice.

i have the question if there are some interactive functions like click one a point, zoom or something like that?
i have a real time line chart and i would need the possibility to click on the chart and get the y and time values of the point i clicked on.

thanks

**Comment by rsandor** [comment]
The question of interactivity with real-time charts is still and open one. Since the chart is moving it seems like a bad idea from a UX perspective (as most interface do not require the user to hit a moving target when clicking or hovering). This being said I wonder if it is even the job of the library to provide this behavior in the first place.

That being said, if you have a sample implementation that does a good job with this, we would always welcome a pull request. For now I am closing this issue.
